version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "devbook"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/data/db